# Generated by Django 5.0.2 on 2024-11-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='work_type',
            field=models.CharField(choices=[('contract', 'Contract'), ('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=30),
        ),
    ]
